### ISSUE TITLE
State Diagram Implementation

### ISSUE THREAD

**Issue by jewingo** [ch1pch4p/gmtk2020#3]
Here's an outline of the behaviors for each cat state. Each state is transitioned based on increments in stimulation and relaxation for the cat, which will be dependent on their stats.

**normal:** mills around, prolonged stationary behavior has a "sitting" image associated, trips easily into "excited" state when stimulated with certain toys. Only "sees" elements at a certain angle, hears from a radius. Has probability to engage with objects in view, pursues these objects at greater speed for random amount of time.

**excited:** still has "milling" behavior but prioritizes moving toward objects of interest, lower timeframe for sitting still (no "sitting" image during still periods. Milling speed is still the same but cat "sprints" towards an object of interest; these actions are still determined by probability, the weights are just changed. Has some chance of triggering a "pouncing" action, where the cat sits still and is launched towards a point. 

**angry:** slower "milling" speed, similar weights of movement vs stillness to "normal" state. Radius for "sprinting" is smaller, but sprinting speed is faster. Less interested in cat toys, more interested in sounds and other cats. Hits cats that get close, increasing their agitation; high probability of "tustle" event when colliding with other cats in angry state.

**tired:** completely still for a random amount of time, chance to be roused by calming interactions (pets or whatever the other holdable tool is)

**lazy:** primarily milling behavior, movement toward objects of interest are at same speed as milling speed, though actions can increase stimulation to move out of state. Does not transition back into "tired" state.

**Comment by jewingo** [comment]
So "actions" are decided by probability and the behavior is dictated by modifications inherent to each state. These are multipliers on the base stats of each cat; the stats of the cats also determine how much an action affects their irritability level.

**Comment by snesguy** [comment]
Ok, I think I know how to refactor into this
